@startuml escalar broadcast-api

title Solução para escalar a broadcast-api

actor Cliente as ct #Green
participant "Tallos-Chat-App-v2" as front #LightBlue
participant "Kong" as kg #LightPink

box "Internal Services"
actor Cron as cr #black
participant "megasac-api" as mcApi #LightCoral
participant "broadcast-api" as bcApi #LightCoral
queue "Kafka" as Kafka
end box

box "Databases"
database "tallos-megasac" as dbTallos #LightGreen
end box

@enduml